import { DexCodeTheme } from '../types';

export const BUILTIN_THEMES: DexCodeTheme[] = [
  {
    id: 'dexcode-dark',
    name: 'DexCode Dark (Default)',
    type: 'dark',
    colors: {
      background: '#0f172a',
      sidebarBackground: '#1e293b',
      editorBackground: '#020617',
      titleBarBackground: '#0f172a',
      statusBarBackground: '#020617',
      activeTabBackground: '#020617',
      inactiveTabBackground: '#1e293b',
      textPrimary: '#f8fafc',
      textSecondary: '#94a3b8',
      accent: '#38bdf8',
      accentHover: '#0284c7',
      border: '#334155',
      selection: '#1e3a8a',
      lineHighlight: '#0f172a',
    },
  },
  {
    id: 'synthwave-84',
    name: 'Synthwave \'84 Cyber',
    type: 'dark',
    colors: {
      background: '#262335',
      sidebarBackground: '#241b2f',
      editorBackground: '#262335',
      titleBarBackground: '#1a1825',
      statusBarBackground: '#1a1825',
      activeTabBackground: '#262335',
      inactiveTabBackground: '#241b2f',
      textPrimary: '#f0eff1',
      textSecondary: '#888296',
      accent: '#ff7edb',
      accentHover: '#fe4450',
      border: '#363145',
      selection: '#463465',
      lineHighlight: '#2d2a3e',
    },
  },
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    type: 'dark',
    colors: {
      background: '#2d2a2e',
      sidebarBackground: '#221f22',
      editorBackground: '#2d2a2e',
      titleBarBackground: '#19181a',
      statusBarBackground: '#19181a',
      activeTabBackground: '#2d2a2e',
      inactiveTabBackground: '#221f22',
      textPrimary: '#fcfcfa',
      textSecondary: '#939293',
      accent: '#ffd866',
      accentHover: '#ff6188',
      border: '#403e41',
      selection: '#5b595c',
      lineHighlight: '#3a373b',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    colors: {
      background: '#282a36',
      sidebarBackground: '#21222c',
      editorBackground: '#282a36',
      titleBarBackground: '#191a21',
      statusBarBackground: '#191a21',
      activeTabBackground: '#282a36',
      inactiveTabBackground: '#21222c',
      textPrimary: '#f8f8f2',
      textSecondary: '#6272a4',
      accent: '#bd93f9',
      accentHover: '#ff79c6',
      border: '#44475a',
      selection: '#44475a',
      lineHighlight: '#343746',
    },
  },
  {
    id: 'dexcode-light',
    name: 'DexCode Crisp Light',
    type: 'light',
    colors: {
      background: '#f8fafc',
      sidebarBackground: '#f1f5f9',
      editorBackground: '#ffffff',
      titleBarBackground: '#e2e8f0',
      statusBarBackground: '#cbd5e1',
      activeTabBackground: '#ffffff',
      inactiveTabBackground: '#e2e8f0',
      textPrimary: '#0f172a',
      textSecondary: '#64748b',
      accent: '#0284c7',
      accentHover: '#0369a1',
      border: '#cbd5e1',
      selection: '#bae6fd',
      lineHighlight: '#f1f5f9',
    },
  },
];

export function getThemeById(id: string): DexCodeTheme {
  return BUILTIN_THEMES.find((t) => t.id === id) || BUILTIN_THEMES[0];
}
